# Generated by Django 2.2.2 on 2019-06-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190606_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='transit_time',
            field=models.CharField(default=50, max_length=21, verbose_name='配送时间'),
            preserve_default=False,
        ),
    ]
