# Generated by Django 2.2.2 on 2019-06-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderinfo_transit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='transit_time',
            field=models.IntegerField(default=30, verbose_name='配送时间'),
        ),
    ]
